name: Deploy to AWS EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Deploy to AWS EC2
        run: echo "Deploying to EC2..."  # (We'll update this later)
